name: pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.9.0
      - run: ./dev env
      - run: ./dev build docker
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.9.0
      - run: ./dev env
      - run: ./dev fmt check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.9.0
      - run: ./dev env
      # Test coverage https://deno.land/manual@v1.9.0/testing#test-coverage
      - run: ./dev test --coverage=cov_profile --unstable
      - run: deno coverage cov_profile --lcov --unstable  > cov_profile.lcov
      - uses: codecov/codecov-action@v1
        with:
          files: ./cov_profile.lcov
